<div class="buttons">
    <h2 class="title">Buttons</h2>
    <div class="row">
        <div class="col">
            <button class="btn" type="button">
                <span>ADD TO CART</span>
            </button>
            <button class="btn" type="button" :hover >
                <span>ADD TO CART</span>
            </button>
        </div>

        <div class="col">
            <button class="btn btn-std" type="button">
                <span>STANDARD</span>
            </button>
            <button class="btn btn-std" type="button" :hover >
                <span>STANDARD</span>
            </button>
        </div>

        <div class="col">
            <div class="spinner">
                <span class="sub">-</span>
                <input class="btn-nb" type="number" value="1" step="1" min="1" max="15">
                <span class="add">+</span>
            </div>

            <div class="spinner">
                <span class="sub">-</span>
                <input class="btn-nb" type="number" value="1" step="1" min="1" max="15">
                <span class="add">+</span>
            </div>   
        </div>
    </div>
</div>

<div class="buttons-input">
    <h2 class="title">Checkboxes & Radio Buttons</h2>

</div>

<div class="input-field">
    <h2 class="title">Input Fields</h2>

    
</div>
<div class="navigations">
    <h2 class="title">Navigation</h2>
    
</div>
