
<ul class="my-list">
    <li>1st Element</li>
    <li>2nd Element</li>
    <li>3rd Element</li>
    <li>4th Element</li>
    <li>5th Element</li>
    <li>6th Element</li>
    <li>7th Element</li>
    <li>8th Element</li>
</ul>

<h1>Abc</h1>
<h2>bcd</h2>
<h3>edf</h3>
<h4>ghi</h4>
<p>Toi la ai</p>
<input type="checkbox" :hover/>
<input type="radio" value=""/>
<button type="button" :hover ><span>Button</span></button>
